POST http://127.0.0.1:8000/api/admin HTTP/1.1
Accept: : application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY0NDM4NTgwNiwiZXhwIjoxNjQ0Mzg5NDA2LCJuYmYiOjE2NDQzODU4MDYsImp0aSI6IkkwRXJLblludFh2dlVJeW8iLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.G_HOtl1_ditL23R3FH1sGe6zlmgGI7CEIMzynQDGwWQ
