POST http://127.0.0.1:8000/api/checkToken HTTP/1.1
Accept: : application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY0NjEwNDMwOCwiZXhwIjoxNjQ2MTA3OTA4LCJuYmYiOjE2NDYxMDQzMDgsImp0aSI6IkNTbjBLdkpQSHFTcVdpYkUiLCJzdWIiOjUsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.4ucEBI8aWvD-KG1T5_AZMaunoDoriGaRuOv7q_wUCTc"
