GET  http://127.0.0.1:8000/api/menu HTTP/1.1
content-type: application/json
Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTY0NjAxOTIyOSwiZXhwIjoxNjQ2MDIyODI5LCJuYmYiOjE2NDYwMTkyMjksImp0aSI6InFqNzI3eklsbFN4aFIyTkYiLCJzdWIiOjUsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.96ca8xu6Gddvg96Aus8npwyzlUp8ET4q_L_8C0pZQAg"

